title: Data + Screening Tools
email: your-email@example.com
description: >-
  A collection of data and screening tools for environmental justice and climate action.
baseurl: ""
url: "https://screening-tools.com"
twitter_username: 
github_username:  

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Collections
collections:
  tools:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "tools"
    values:
      layout: "tool"